# Generated by Django 4.0.5 on 2024-01-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hospital',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
